'use strict';

const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
const btnsOpenModal = document.querySelectorAll('.show-modal');

const closeModal = function () {
  modal.classList.add('hidden');
  overlay.classList.add('hidden');
};

const openModal = function () {
  modal.classList.remove('hidden');
  overlay.classList.remove('hidden');
};

for (let i = 0; i < btnsOpenModal.length; i++) {
  btnsOpenModal[i].addEventListener('click', openModal);
}

btnCloseModal.addEventListener('click', closeModal);
overlay.addEventListener('click', closeModal);

// Keyboard events are GLOBAL events.
// To discern which key was pressed, we need to access to the "event"
// that is generated by the listener function
document.addEventListener('keydown', function (e) {
  // e is the event object
  if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
    closeModal(); // We call it, now we are in a function body
  }
});
